# Document: Makefile for Assignment 2: Go-Back-N Protocol
# Author: Lalit Lal
# Date: November 7, 2018

all:
	@echo "Compiling..."
	javac *.java

.PHONY: clean

clean:
	@echo "Cleaning..."
	find . -name "*.class" -delete